server:
  port: 9004

spring:
  #配置数据源信息
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的各个信息
    driver-class-name: com.mysql.jdbc.Driver
    #设置字符集
    url: jdbc:mysql://localhost:3306/sys_test?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
logging:
  level:
    com.plus.mapper: debug
mybatis-plus:
  type-aliases-package: com.entty
  mapper-locations: classpath:mapper/*.xml